### PR TITLE
Add deserialization and validation of parameters - #67

### PR DESCRIPTION
**Pull request by dz-1**
Deserialized values can be accessed through static helper methods as below:
- OpenApiHandler.getQueryParameters(exchange, true)
- OpenApiHandler.getPathParameters(exchange, true)
- OpenApiHandler.getHeaderParameters(exchange, true)
- OpenApiHandler.getCookieParameters(exchange, true)

The below helper methods return all available parameter values:
- OpenApiHandler.getQueryParameters(exchange)
- OpenApiHandler.getPathParameters(exchange)
- OpenApiHandler.getHeaderParameters(exchange)
- OpenApiHandler.getCookieParameters(exchange)

Arrays and objects are validated against deserialized values when necessary. The deserialization is supported to the extent of the examples in the [openapi serialization doc](https://swagger.io/docs/specification/serialization/.) 

Usage examples can be found in `/openapi-validator/src/test/java/com/networknt/openapi/RequestValidatorTest.java`.

### CODE REVIEW

**Comment by stevehu** [comment]
@Dasanko Could you please review the fix? Thanks.

**Comment by Dasanko** [comment]
How can I go about testing this? It's not playing nicely as-is with light-codegen.

**Comment by stevehu** [comment]
@Dasanko could you please elaborate? Do you mean that the light-codegen cannot generate a project from your specification?

**Comment by stevehu** [comment]
@Dasanko, @dz-1 has updated the TestProject.yaml you have provided and I have checked it into the model-config repository. The light-codegen can generate the project successfully. 

https://github.com/networknt/model-config/tree/master/rest/openapi/json-query-param

And here is the change. https://github.com/networknt/model-config/issues/52

**Comment by Dasanko** [comment]
Sorry, I've been busy.
Seems to be working fine now, thanks!

Here are my findings:
curl -k -X GET https://localhost:8443/api/testEndPoint?TestObject={testProperty=testing} (fails, as expected, it's not part of the standard)
curl -k -X GET https://localhost:8443/api/testEndPoint?TestObject=testProperty,testing (fails, should it be supported as well? Not very important)
curl -k -X GET https://localhost:8443/api/testEndPoint?testProperty=testing (passes)
curl -k -X GET https://localhost:8443/api/testEndPoint?TestObject[testProperty]=testing (passes)

**Comment by stevehu** [comment]
@Dasanko I think you are testing from the master branch. The code is not merged into the master yet. I have tested all scenarios above and documented at https://doc.networknt.com/tutorial/rest/openapi/parameter-serialization/json-query-param/

**Comment by Dasanko** [comment]
@stevehu My bad, you're right. I had replaced light-codegen's (master branch) files with the new ones from model-config.
It is working fine, thank you!

**Pull request merged**
